# Generated by Django 5.1.15 on 2026-06-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(help_text='e.g. Block A', max_length=50)),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('1_in_a_room', '1-in-a-room'), ('2_in_a_room', '2-in-a-room'), ('4_in_a_room', '4-in-a-room')], default='2_in_a_room', max_length=20)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_generator', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('block', 'room_number'),
                'unique_together': {('block', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='BedSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_label', models.CharField(help_text='e.g. Bed 1', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('occupant_ref', models.IntegerField(blank=True, null=True)),
                ('booking_ref', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='tenants.room')),
            ],
            options={
                'ordering': ('room', 'bed_label'),
                'unique_together': {('room', 'bed_label')},
            },
        ),
    ]
