# Generated by Django 5.1.15 on 2026-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1_in_a_room', '1-in-a-room'), ('2_in_a_room', '2-in-a-room'), ('3_in_a_room', '3-in-a-room'), ('4_in_a_room', '4-in-a-room'), ('6_in_a_room', '6-in-a-room')], default='2_in_a_room', max_length=20),
        ),
    ]
