# Generated by Django 5.1.15 on 2026-06-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0003_globalbooking_approved_at_payment_manager_payout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenanthostel',
            name='gender_policy',
            field=models.CharField(choices=[('mixed', 'Mixed'), ('male', 'Male only'), ('female', 'Female only')], default='mixed', max_length=10),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_electricity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='min_stay_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum stay in months'),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='utilities_included',
            field=models.BooleanField(default=False, help_text='Are utility bills included in the listed price?'),
        ),
    ]
