# Generated by Django 5.1.15 on 2026-06-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0004_hostel_amenity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenanthostel',
            name='campus',
            field=models.CharField(choices=[('UG', 'University of Ghana, Legon'), ('KNUST', 'Kwame Nkrumah University of Science and Technology (KNUST)'), ('UCC', 'University of Cape Coast (UCC)'), ('UDS', 'University for Development Studies (UDS)'), ('UEW', 'University of Education, Winneba (UEW)'), ('UPSA', 'University of Professional Studies, Accra (UPSA)'), ('UHAS', 'University of Health and Allied Sciences (UHAS)'), ('UESD', 'University of Environment and Sustainable Development (UESD)'), ('CKTCUTAS', 'C.K. Tedam University of Technology and Applied Sciences (CKT-UTAS)'), ('SDDBIDS', 'SD Dombo University of Business and Integrated Development Studies (SDD-UBIDS)'), ('AAMUSTED', 'Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development (AAMUSTED)'), ('UMAT', 'University of Mines and Technology (UMaT)'), ('GIMPA', 'Ghana Institute of Management and Public Administration (GIMPA)'), ('ATU', 'Accra Technical University'), ('HTU', 'Ho Technical University'), ('KTU', 'Kumasi Technical University'), ('CCTU', 'Cape Coast Technical University'), ('STU', 'Sunyani Technical University'), ('TTTU', 'Tamale Technical University'), ('TATU', 'Takoradi Technical University'), ('WTU', 'Wa Technical University'), ('KofTU', 'Koforidua Technical University'), ('BTU', 'Bolgatanga Technical University'), ('ASHESI', 'Ashesi University'), ('CENTRAL', 'Central University'), ('VVU', 'Valley View University'), ('GCUC', 'Ghana Christian University College'), ('MUG', 'Methodist University Ghana'), ('TTS', 'Trinity Theological Seminary'), ('REGENT', 'Regent University College of Science and Technology'), ('PACU', 'Pan-African Christian University College'), ('ACC', 'Academic City College'), ('WIUC', 'Wisconsin International University College'), ('GCTU', 'Ghana Communication Technology University (GCTU)'), ('CUCG', 'Catholic University College of Ghana'), ('PUCG', 'Presbyterian University College Ghana'), ('PU', 'Pentecost University'), ('HCC', 'Heritage Christian College'), ('AIT', 'Accra Institute of Technology (AIT)'), ('BLUECREST', 'BlueCrest University College'), ('ANOVA', 'ANova Education'), ('MOUNT', 'Mountcrest University College'), ('DOMINION', 'Dominion University College'), ('ANU', 'All Nations University'), ('GBUC', 'Ghana Baptist University College'), ('ZENITH', 'Zenith University College'), ('SPIRITAN', 'Spiritan University College'), ('IUCG', 'Islamic University College Ghana'), ('LANCASTER', 'Lancaster University Ghana'), ('WEBSTER', 'Webster University Ghana'), ('SMC', 'Swiss Management Centre (SMC) University Ghana'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
