# Generated by Django 5.1.15 on 2026-06-18 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0006_managerverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('msg_broadcast', 'Broadcast Message'), ('msg_direct', 'Direct Message'), ('report', 'Maintenance Report'), ('booking_paid', 'Booking Payment Received'), ('booking_approved', 'Booking Approved'), ('booking_cancelled', 'Booking Cancelled'), ('hostel_verified', 'Hostel Verified'), ('hostel_activated', 'Hostel Activated'), ('hostel_deactivated', 'Hostel Deactivated'), ('verif_approved', 'Verification Approved'), ('verif_rejected', 'Verification Rejected')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='global_app__recipie_6d1e4e_idx')],
            },
        ),
    ]
