# Generated by Django 5.1.15 on 2026-06-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0009_hostel_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenanthostel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenanthostel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
