# Generated by Django 5.1.15 on 2026-06-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0010_hostel_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalbooking',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalbooking',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
