# Generated by Django 5.1.15 on 2026-06-21 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_app', '0011_booking_stay_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('msg_broadcast', 'Broadcast Message'), ('msg_direct', 'Direct Message'), ('report', 'Maintenance Report'), ('booking_paid', 'Booking Payment Received'), ('booking_approved', 'Booking Approved'), ('booking_cancelled', 'Booking Cancelled'), ('hostel_verified', 'Hostel Verified'), ('hostel_activated', 'Hostel Activated'), ('hostel_deactivated', 'Hostel Deactivated'), ('verif_approved', 'Verification Approved'), ('verif_rejected', 'Verification Rejected'), ('waitlist_notified', 'Waitlist — Bed Available'), ('renewal_reminder', 'Renewal Reminder')], max_length=30),
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_schedule', models.CharField(blank=True, choices=[('early', 'Early bird (before 10 pm)'), ('normal', 'Normal (10 pm – midnight)'), ('night', 'Night owl (after midnight)')], max_length=10)),
                ('study_habit', models.CharField(blank=True, choices=[('quiet', 'I study in silence'), ('music', 'I study with music/low noise'), ('social', 'I prefer group study')], max_length=10)),
                ('is_smoker', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('is_visible', models.BooleanField(default=True, help_text='Show profile to other students at this hostel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profiles', to='global_app.tenanthostel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoommateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_app.tenanthostel')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_roommate_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_roommate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('sender', 'receiver', 'hostel')},
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='global_app.tenanthostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('hostel', 'room_type', 'position'),
                'indexes': [models.Index(fields=['hostel', 'room_type', 'position'], name='global_app__hostel__f12a4d_idx')],
                'unique_together': {('student', 'hostel', 'room_type')},
            },
        ),
    ]
