// Registers the service worker generated by vite-plugin-pwa.
// The virtual module is provided by the plugin at build/dev time.
export function registerSW() {
  if (typeof window === "undefined") return;
  // Dynamically import so the app still runs if the virtual module is absent
  // (e.g. plugin disabled). In production this wires up auto-update.
  import("virtual:pwa-register")
    .then(({ registerSW }) => {
      registerSW({ immediate: true });
    })
    .catch(() => {
      /* PWA registration unavailable; app works without it. */
    });
}
